# Generated by Django 3.2.12 on 2022-04-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id_conteudo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sinopse', models.CharField(max_length=300)),
                ('elenco', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('data_lancamento', models.DateTimeField(verbose_name='data de lancamento')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.conteudo')),
                ('user_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id_quizz', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo_quizz', models.CharField(max_length=100)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.conteudo')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_texto', models.CharField(max_length=200)),
                ('opcao_correta', models.BooleanField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.questao')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.CharField(max_length=250)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.conteudo')),
                ('user_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
