# Generated by Django 3.2.12 on 2022-04-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='quizz',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.quizz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizz',
            name='conteudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.conteudo'),
        ),
    ]
